name: Android CI

on:
  push:
    branches: [ "main", "v*/**"]
  pull_request:
    branches: [ "main" , "v*/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Prepare Artifact
      if: success()
      id: prepareArtifact
      run: |
        releaseArtifactName=`ls app/build/outputs/apk/release/*.apk | grep -Po "(?<=release/).*(?=\.apk)"` && echo "releaseArtifactName=$releaseArtifactName" >> $GITHUB_OUTPUT
        debugArtifactName=`ls app/build/outputs/apk/debug/*.apk | grep -Po "(?<=debug/).*(?=\.apk)"` && echo "debugArtifactName=$debugArtifactName" >> $GITHUB_OUTPUT

    - name: Upload Archive Release-Apk
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepareArtifact.outputs.releaseArtifactName }}
        path: app/build/outputs/apk/release/*.apk

    - name: Upload Archive Debug-Apk
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepareArtifact.outputs.debugArtifactName }}
        path: ./app/build/outputs/apk/debug/*.apk
